version: "3"

services:

  kong:
    build:
      context: ../api-gateway
      dockerfile: Dockerfile
    image: tocandira_kong:0.1.1
    
  frontend:
    container_name: frontend
    build:
      dockerfile: Dockerfile
      context: ../front
    image: tocandira_frontend:0.1.0
    
  backend:
    container_name: backend
    build:
      dockerfile: Dockerfile
      context: ../back
    image: tocandira_backend:0.1.0
    
  watchdog:
    container_name: watchdog
    build:
      dockerfile: Dockerfile
      context: ../watchdog
    image: tocandira_watchdog:0.2.0
    