# Copyright (c) 2017 Aimirim STI.

_format_version: "1.1"

services:
  - name: grafana
    url: http://grafana:3000

  - name: frontend
    url: http://frontend:8000

  - name: backend
    url: http://backend:8000

routes:
  - name: grafana
    service: grafana
    preserve_host: true
    paths:
    - /

  - name: frontend
    service: frontend
    preserve_host: true
    paths:
    - /admin

  - name: backend
    service: backend
    preserve_host: true
    paths:
    - /admin/api/v0
    
plugins:
  - name: bot-detection
